### ISSUE TITLE
叫 showLayers 是因为一次可以展示多个层？

### ISSUE THREAD

**Issue by cssmagic** [huberystyle/showLayers#1]
如果不是，还是叫 `showLayer` 比较好哦。

**Comment by huberystyle** [comment]
对的，可以同时展开多个层，层上可以弹层。

**Comment by cssmagic** [comment]
我的意思是 `.showLayers()` 这个接口一次可以打开多个层吗？

我看了源码，用了 `.each()`，好像真的可以。 :open_mouth:

**Comment by huberystyle** [comment]
可以的，只要调用了，想打开几个就打开几个，不论用什么事件触发。
